services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SchemaBundle\EventListener\SchemaListener:
        tags:
            - { name: kernel.event_subscriber }