services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    SchemaBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('SchemaBundle')"
        calls:
            - [setTokenStorageUserResolver, ['@Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver']]
            - [setSerializer, ['@serializer']]
