services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SchemaBundle\Twig\Extension\JsonLdExtension:
        tags:
            - { name: twig.extension }