services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SchemaBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('SchemaBundle')"
