services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SchemaBundle\Registry\SchemaGeneratorRegistryInterface: '@SchemaBundle\Registry\SchemaGeneratorRegistry'
    SchemaBundle\Registry\SchemaGeneratorRegistry:
        arguments:
            $generatorInterface: SchemaBundle\Generator\GeneratorInterface
            $fragmentGeneratorInterface: SchemaBundle\Generator\FragmentGeneratorInterface
